stages:
  - build
  - test
  - package

build-dotnet:
  stage: build
  tags:
    - short-jobs
  image: microsoft/dotnet:2.2-sdk
  script:
    - dotnet restore
    - dotnet publish -c Debug -o build
  artifacts:
    untracked: false
    paths:
      - ingress-app/build/

test-dotnet:
  stage: test
  tags:
    - short-jobs
  image: microsoft/dotnet:2.2-sdk
  services:
    - influxdb
  script:
    - curl -i -XPOST http://influxdb:8086/query --data-urlencode "q=CREATE DATABASE telemetry"
    - dotnet restore
    - dotnet build
    - dotnet test

package-docker:
  stage: package
  image: docker
  tags:
    - short-jobs
  dependencies:
    - build-dotnet
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME  .
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:latest


